version: "3.9"
services:
  web:
    build: ./flask/
    image: flask_image
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./flask:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app:app
      - FLASK_RUN_CERT=cert.pem
      - FLASK_RUN_KEY=key.pem
    command: ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]

   mysql:
    build: ./mysql/
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
